---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - egress.github.com
  resources:
  - egresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egress.github.com
  resources:
  - egresses/finalizers
  verbs:
  - update
- apiGroups:
  - egress.github.com
  resources:
  - egresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - egress.github.com
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egress.github.com
  resources:
  - namespaces/status
  verbs:
  - get
- apiGroups:
  - egress.github.com
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - egress.github.com
  resources:
  - pods/status
  verbs:
  - get
